apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/davmano/k8s-gitops-repo'
    targetRevision: HEAD
    path: flask-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: flask-app
  syncPolicy:
    automated: {}           # auto-deploy when Git changes
