apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-aws-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-container
          image: davmano/flask-app_sm:0035870
          ports:
            - containerPort: 5000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_NAME
            - name: MY_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MY_SECRET
            - name: AWS_SECRET_NAME
              value: "my-aws-secret"  # Name of the AWS Secrets Manager secret
